### PR TITLE
Upgrade wakatime-cli to 13.1.0

### PR DESCRIPTION
**Pull request by zchee**
Upgrade wakatime-cli to 13.1.0, which latest of https://github.com/wakatime/wakatime.

### CODE REVIEW

**Comment by alanhamlett** [comment]
Let's skip this wakatime-cli version as we plan to go straight to the new Go language wakatime-cli that we're releasing soon.

**Comment by zchee** [comment]
wakatime-cli written in Go is very interesting! My main language is Go, so will contribute for giving back very awesome tools, wakatime!

**Comment by alanhamlett** [comment]
Cool, I just added you to the repo so you can try it out in your Vim if you like.

**Pull request closed without merging**
