### PR TITLE
feat(api): custom api url

### PR DESCRIPTION
**Pull request by Mte90**
Added support for the `api_url` parameter in the config file.

### CODE REVIEW

**Comment by alanhamlett** [comment]
Api url param is already supported with no change necessary. That's because wakatime-cli reads the config file on it's own, and uses `api_url` from there directly. The `--api-url` param is just a way to override the config file.

**Comment by Mte90** [comment]
I investigated a bit. Seems that in wakatime you put the domain as this is cross compatible between various plugins for the various editors.
Instead this plugin require the full url to `https://api.wakatime.com/api/v1/users/current/heartbeats.bulk` as example.

This creates 404 because don't generate the whole url for the API.

The first part of the pr it was right infact now works. Can I do a new pr with that change or you will do it a commit for it?

**Comment by alanhamlett** [comment]
We shouldn't need a PR in vim-wakatime, because reading the `api_url` config from `~/.wakatime.cfg` happens in [wakatime-cli](https://github.com/wakatime/wakatime-cli) and never needs vim-wakatime.

**Comment by Mte90** [comment]
So I will open a an issue on that project.
In the meantime I am using a patched version of the plugin as I don't know Go language.

**Pull request closed without merging**
